--Imperial
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '-5', '1.5 lb.', '1/8 second', '6 inches', '1/32 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '-4', '3 lbs.', '1/4 second', '1 foot', '1/16 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '-3', '6 lbs.', '1/2 second', '3 feet', '1/8 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '-2', '12 lbs.', '1 second', '6 feet', '1/4 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '-1', '25 lbs.', '3 seconds', '15 feet', '1/2 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '0', '50 lbs.', '6 seconds', '30 feet', '1 cubic ft. (cft.)');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '1', '100 lbs.', '12 seconds', '60 feet', '2 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '2', '200 lbs.', '30 seconds', '120 feet', '4 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '3', '400 lbs.', '1 minute', '250 feet', '8 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '4', '800 lbs.', '2 minutes', '500 feet', '15 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '5', '1,600 lbs.', '4 minutes', '900 feet', '30 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '6', '3,200 lbs.', '8 minutes', '1,800 feet', '60 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '7', '3 tons', '15 minutes', '1/2 mile', '125 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '8', '6 tons', '30 minutes', '1 mile', '250 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '9', '12 tons', '1 hour', '2 miles', '500 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '10', '25 tons', '2 hours', '4 miles', '1,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '11', '50 tons', '4 hours', '8 miles', '2,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '12', '100 tons', '8 hours', '16 miles', '4,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '13', '200 tons', '16 hours', '30 miles', '8,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '14', '400 tons', '1 day', '60 miles', '15,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '15', '800 tons', '2 days', '120 miles', '32,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '16', '1,600 tons', '4 days', '250 miles', '65,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '17', '3.2 ktons', '1 week', '500 miles', '125,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '18', '6 ktons', '2 weeks', '1,000 miles', '250,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '19', '12 ktons', '1 month', '2,000 miles', '500,000 cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '20', '25 ktons', '2 months', '4,000 miles', '1 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '21', '50 ktons', '4 months', '8,000 miles', '2 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '22', '100 ktons', '8 months', '16,000 miles', '4 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '23', '200 ktons', '1.5 years', '32,000 miles', '8 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '24', '400 ktons', '3 years', '64,000 miles', '15 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '25', '800 ktons', '6 years', '125,000 miles', '32 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '26', '1,600 ktons', '12 years', '250,000 miles', '65 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '27', '3,200 ktons', '25 years', '500,000 miles', '125 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '28', '6,400 ktons', '50 years', '1 million miles', '250 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '29', '12,500 ktons', '100 years', '2 million miles', '500 million cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '30', '25,000 ktons', '200 years', '4 million miles', '1 billion cft.');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('imperial', '+1', 'x2', 'x2', 'x2', 'x2');

--Metric
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '-5', '750 grams', '1/8 second', '15 cm', '.0008 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '-4', '1.5 kg', '1/4 second', '50 cm', '.0017 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '-3', '3 kg', '1/2 second', '1 m', '.0035 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '-2', '6 kg', '1 second', '2 m', '.007 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '-1', '12 kg', '3 seconds', '4 m', '.014 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '0', '24 kg', '6 seconds', '8 m', '.025 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '1', '50 kg', '12 seconds', '16 m', '.05 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '2', '100 kg', '30 seconds', '32 m', '.1 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '3', '200 kg', '1 minute', '64 m', '.2 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '4', '400 kg', '2 minutes', '125 m', '.4 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '5', '800 kg', '4 minutes', '250 m', '.8 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '6', '1600 kg', '8 minutes', '500 m', '1.7 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '7', '3.2 tons', '15 minutes', '1 km', '3.5 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '8', '6 tons', '30 minutes', '2 km', '7 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '9', '12 tons', '1 hour', '4 km', '15 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '10', '25 tons', '2 hours', '8 km', '30 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '11', '50 tons', '4 hours', '16 km', '60 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '12', '100 tons', '8 hours', '32 km', '120 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '13', '200 tons', '16 hours', '64 km', '250 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '14', '400 tons', '1 day', '125 km', '500 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '15', '800 tons', '2 days', '250 km', '1,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '16', '1,600 tons', '4 days', '500 km', '2,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '17', '3.2 ktons', '1 week', '1,000 km', '4,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '18', '6 ktons', '2 weeks', '2,000 km', '8,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '19', '12 ktons', '1 month', '4,000 km', '15,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '20', '25 ktons', '2 months', '8,000 km', '30,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '21', '50 ktons', '4 months', '16,000 km', '60,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '22', '100 ktons', '8 months', '32,000 km', '120,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '23', '200 ktons', '1.5 years', '64,000 km', '250,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '24', '400 ktons', '3 years', '125,000 km', '500,000 m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '25', '800 ktons', '6 years', '250,000 km', '1 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '26', '1,600 ktons', '12 years', '500,000 km', '2 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '27', '3,200 ktons', '25 years', '1 million km', '4 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '28', '6,400 ktons', '50 years', '2 million km', '8 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '29', '12,500 ktons', '100 years', '4 million km', '15 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '30', '25,000 ktons', '200 years', '8 million km', '30 million m³');
INSERT INTO measurements (MeasurementType, Rank, Mass, Time, Distance, Volume) VALUES ('metric', '+1', 'x2', 'x2', 'x2', 'x2');